/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import static wawonpahlawan.Barang.tampilkan;
import static wawonpahlawan.Supplier.tampilkan;
/**
 *
 * @author Aryaaazr_
 */
public class DaftarKategori extends javax.swing.JFrame {

    /**
     * Creates new form DaftarBarang
     */
    static DefaultTableModel model;
    static String id_kategori;
    static String nama_kategori;
    public DaftarKategori() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tb_daftarkategori.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tb_daftarkategori.getTableHeader().setOpaque(false);
        tb_daftarkategori.getTableHeader().setBackground(new Color(34, 48, 96));
        tb_daftarkategori.getTableHeader().setForeground(new Color(255,255,255));
        tb_daftarkategori.getRowHeight(25);
        tampilkan();
    }
    public void reset(){
        idKategori.setText("");
        namaKategori.setText("");
    }
    public static void tampilkan() {
        String [] judul = {"ID Kategori","Nama Kategori"};
        model = new DefaultTableModel(judul,0);
        tb_daftarkategori.setModel(model);
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_kategori");
            while(rs.next()){
                String data [] = {rs.getString(1),rs.getString(2)};
                model.addRow(data);
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tb_daftarkategori = new javax.swing.JTable();
        namaKategori = new javax.swing.JTextField();
        idKategori = new javax.swing.JTextField();
        labelNamaKategori = new javax.swing.JLabel();
        labelIdKategori = new javax.swing.JLabel();
        fieldNamaKategori = new javax.swing.JLabel();
        fieldIdKategori = new javax.swing.JLabel();
        btnTambah = new javax.swing.JLabel();
        btnEdit = new javax.swing.JLabel();
        btnHapus = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_daftarkategori.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tb_daftarkategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_daftarkategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_daftarkategoriMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_daftarkategori);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 580, 220));

        namaKategori.setBorder(null);
        namaKategori.setOpaque(false);
        getContentPane().add(namaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 120, 170, 30));

        idKategori.setBorder(null);
        idKategori.setOpaque(false);
        getContentPane().add(idKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 130, 30));

        labelNamaKategori.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelNamaKategori.setForeground(new java.awt.Color(34, 48, 96));
        labelNamaKategori.setText("Nama Kategori");
        getContentPane().add(labelNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, -1, 30));

        labelIdKategori.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        labelIdKategori.setForeground(new java.awt.Color(34, 48, 96));
        labelIdKategori.setText("ID Kategori");
        getContentPane().add(labelIdKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, 30));

        fieldNamaKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text field nama kategori.png"))); // NOI18N
        getContentPane().add(fieldNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 190, 30));

        fieldIdKategori.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/text fielld id barang.png"))); // NOI18N
        getContentPane().add(fieldIdKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, -1, 30));

        btnTambah.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/add (4) 1.png"))); // NOI18N
        btnTambah.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambah.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTambah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTambahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTambahMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTambahMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTambahMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTambahMouseReleased(evt);
            }
        });
        getContentPane().add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 160, 60, 60));

        btnEdit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/edit-text 1.png"))); // NOI18N
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEditMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEditMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnEditMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnEditMouseReleased(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 60, 60));

        btnHapus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/delete (2) 1.png"))); // NOI18N
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHapusMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHapusMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHapusMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnHapusMouseReleased(evt);
            }
        });
        getContentPane().add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 160, 60, 60));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Frame 13.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_daftarkategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_daftarkategoriMouseClicked
       int row = tb_daftarkategori.getSelectedRow();
        this.id_kategori = tb_daftarkategori.getValueAt(row, 0).toString();
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            ResultSet rs = con.createStatement().executeQuery("SELECT * FROM tb_kategori WHERE id_kategori ='"+id_kategori+"'");
            while(rs.next()){
                idKategori.setText(rs.getString("id_kategori"));
                namaKategori.setText(rs.getString("nama_kategori"));
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_daftarkategoriMouseClicked

    private void btnTambahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseClicked
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            try{
                Long.parseLong(idKategori.getText());
            } 
            catch(Exception e){
                JOptionPane.showMessageDialog(null,"Masukkan id kategori dengan benar" );
            }
            String nama = namaKategori.getText();
            PreparedStatement ps = con.prepareStatement("INSERT INTO tb_kategori VALUES('"+ Long.parseLong(idKategori.getText()) + "','"+nama+"')");
            ps.execute();
            JOptionPane.showMessageDialog(null,"Data kategori berhasil ditambahkan");
            tampilkan();
            reset();
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Kategori telah terdaftar");
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnTambahMouseClicked

    private void btnTambahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseEntered
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseEntered

    private void btnTambahMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseExited
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah.png")));
    }//GEN-LAST:event_btnTambahMouseExited

    private void btnEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseClicked
        try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            String idkategori=idKategori.getText();
            String nama=namaKategori.getText();
            String id_kategori="";
            if (idKategori.getText()==null) {
                JOptionPane.showMessageDialog(null,"Masukkan data kategori dengan benar" );
            } else {
                PreparedStatement ps = con.prepareStatement("UPDATE tb_kategori SET nama_kategori = '"+nama+"' WHERE id_kategori = '"+idkategori+"'");
                ps.execute();
                JOptionPane.showMessageDialog(null,"Data kategori berhasil diedit");
                tampilkan();
                reset();
            }
        }
        catch (SQLException ex){
            Logger.getLogger(Karyawan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEditMouseClicked

    private void btnEditMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseEntered
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseEntered

    private void btnEditMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseExited
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit.png")));
    }//GEN-LAST:event_btnEditMouseExited

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
       try{
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/db_coolinarypos","root","");
            String idkategori=idKategori.getText();
            String nama = namaKategori.getText();
            String id_kategori="";
            if (idKategori.getText()==null) {
                JOptionPane.showMessageDialog(null,"Masukkan data kategori dengan benar" );
            } else {
                PreparedStatement ps = con.prepareStatement("DELETE FROM tb_kategori WHERE id_kategori = '"+idkategori+"'");
                ps.execute();
                JOptionPane.showMessageDialog(null,"Data kategori berhasil dihapus");
                tampilkan();
                reset();
            }
        }
        catch (SQLException ex){
            JOptionPane.showMessageDialog(null,"Tidak bisa dihapus karena terdapat data kategori di transaksi");
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
    }                    
    }//GEN-LAST:event_btnHapusMouseClicked

    private void btnHapusMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseEntered
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseEntered

    private void btnHapusMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseExited
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus.png")));
    }//GEN-LAST:event_btnHapusMouseExited

    private void btnTambahMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMousePressed
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Press.png")));
    }//GEN-LAST:event_btnTambahMousePressed

    private void btnTambahMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTambahMouseReleased
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Tambah_Hover.png")));
    }//GEN-LAST:event_btnTambahMouseReleased

    private void btnEditMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMousePressed
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Press.png")));
    }//GEN-LAST:event_btnEditMousePressed

    private void btnEditMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEditMouseReleased
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Edit_Hover.png")));
    }//GEN-LAST:event_btnEditMouseReleased

    private void btnHapusMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMousePressed
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Press.png")));
    }//GEN-LAST:event_btnHapusMousePressed

    private void btnHapusMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseReleased
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Hapus_Hover.png")));
    }//GEN-LAST:event_btnHapusMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarKategori.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarKategori().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnEdit;
    private javax.swing.JLabel btnHapus;
    private javax.swing.JLabel btnTambah;
    private javax.swing.JLabel fieldIdKategori;
    private javax.swing.JLabel fieldNamaKategori;
    private javax.swing.JTextField idKategori;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelIdKategori;
    private javax.swing.JLabel labelNamaKategori;
    private javax.swing.JTextField namaKategori;
    private static javax.swing.JTable tb_daftarkategori;
    // End of variables declaration//GEN-END:variables
}
