/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import config.Config;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Aryaaazr_
 */
public class Navbar extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    String id,  status;
    public Navbar(String username, String Status) {
        id = username;  //mengambil parameter admin id
        status = Status;    //mengambil nilai parameter hak akses
        //validasi apakah sudah login atau belum
        if (username == null) {
             JOptionPane.showMessageDialog(null, "Silahkan login terlebih dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
             new Login().setVisible(true);
        }
        Config db = new Config();   //instansiasi class Conn()
        initComponents();
        setLocationRelativeTo(this);    // atur jframe berada ditengah
        setExtendedState(MAXIMIZED_BOTH);   // full Jframe
        getUsername(username);  //menjalankan method getUsername dengan parameter nama admin dari navbar
        getStatus(Status);  // menjalankan method getStatus dengan parameter status dari navbar
        
    }
    
    //setter nama admin di pojok kanan atas
    public void getUsername(String username){
        labelUsername.setText(Login.namapengguna);
    }
    public void getStatus(String Status) {
        labelStatus.setText(Status);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        profilePanel = new javax.swing.JPanel();
        profilePicture = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelStatus = new javax.swing.JLabel();
        btnBarang = new javax.swing.JPanel();
        labelBarang = new javax.swing.JLabel();
        iconBarang = new javax.swing.JLabel();
        btnTransaksi = new javax.swing.JPanel();
        labelTransaksi = new javax.swing.JLabel();
        iconTransaksi = new javax.swing.JLabel();
        btnKaryawan = new javax.swing.JPanel();
        labelKaryawan = new javax.swing.JLabel();
        iconKaryawan = new javax.swing.JLabel();
        btnSupplier = new javax.swing.JPanel();
        labelTransaksi2 = new javax.swing.JLabel();
        iconSupplier = new javax.swing.JLabel();
        btnStatistik = new javax.swing.JPanel();
        labelStatistik = new javax.swing.JLabel();
        iconStatistik = new javax.swing.JLabel();
        btnSetting = new javax.swing.JPanel();
        labelSetting = new javax.swing.JLabel();
        iconSetting = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JPanel();
        labelDashboard = new javax.swing.JLabel();
        iconDashboard = new javax.swing.JLabel();
        DesktopPane = new javax.swing.JDesktopPane();
        navbar1 = new javax.swing.JPanel();
        logoAplikasi = new javax.swing.JLabel();
        judul = new javax.swing.JLabel();
        btn_close = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sideBar.setBackground(new java.awt.Color(34, 48, 96));

        profilePanel.setBackground(new java.awt.Color(101, 113, 156));

        profilePicture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/user 1_1.png"))); // NOI18N

        labelUsername.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setText("Username");

        labelStatus.setFont(new java.awt.Font("Arial", 2, 24)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(255, 255, 255));
        labelStatus.setText("Status");

        javax.swing.GroupLayout profilePanelLayout = new javax.swing.GroupLayout(profilePanel);
        profilePanel.setLayout(profilePanelLayout);
        profilePanelLayout.setHorizontalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(profilePicture)
                .addGap(18, 18, 18)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        profilePanelLayout.setVerticalGroup(
            profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(profilePanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(profilePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(profilePicture, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(profilePanelLayout.createSequentialGroup()
                        .addComponent(labelUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        btnBarang.setBackground(new java.awt.Color(34, 48, 96));
        btnBarang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBarangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBarangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBarangMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnBarangMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnBarangMouseReleased(evt);
            }
        });

        labelBarang.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelBarang.setForeground(new java.awt.Color(255, 255, 255));
        labelBarang.setText("Barang");

        iconBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/barang 2_5.png"))); // NOI18N

        javax.swing.GroupLayout btnBarangLayout = new javax.swing.GroupLayout(btnBarang);
        btnBarang.setLayout(btnBarangLayout);
        btnBarangLayout.setHorizontalGroup(
            btnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBarangLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelBarang)
                .addContainerGap(189, Short.MAX_VALUE))
        );
        btnBarangLayout.setVerticalGroup(
            btnBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnTransaksi.setBackground(new java.awt.Color(34, 48, 96));
        btnTransaksi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnTransaksiMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnTransaksiMouseReleased(evt);
            }
        });

        labelTransaksi.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelTransaksi.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi.setText("Transaksi");

        iconTransaksi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Icon shoping 2.png"))); // NOI18N

        javax.swing.GroupLayout btnTransaksiLayout = new javax.swing.GroupLayout(btnTransaksi);
        btnTransaksi.setLayout(btnTransaksiLayout);
        btnTransaksiLayout.setHorizontalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnTransaksiLayout.setVerticalGroup(
            btnTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnTransaksiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnKaryawan.setBackground(new java.awt.Color(34, 48, 96));
        btnKaryawan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnKaryawanMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnKaryawanMouseReleased(evt);
            }
        });

        labelKaryawan.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelKaryawan.setForeground(new java.awt.Color(255, 255, 255));
        labelKaryawan.setText("Karyawan");

        iconKaryawan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/employees 1_1.png"))); // NOI18N

        javax.swing.GroupLayout btnKaryawanLayout = new javax.swing.GroupLayout(btnKaryawan);
        btnKaryawan.setLayout(btnKaryawanLayout);
        btnKaryawanLayout.setHorizontalGroup(
            btnKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKaryawanLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelKaryawan)
                .addContainerGap(164, Short.MAX_VALUE))
        );
        btnKaryawanLayout.setVerticalGroup(
            btnKaryawanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnKaryawanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSupplier.setBackground(new java.awt.Color(34, 48, 96));
        btnSupplier.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSupplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSupplierMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSupplierMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSupplierMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSupplierMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSupplierMouseReleased(evt);
            }
        });

        labelTransaksi2.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelTransaksi2.setForeground(new java.awt.Color(255, 255, 255));
        labelTransaksi2.setText("Supplier");

        iconSupplier.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/delivery-man 1_1.png"))); // NOI18N

        javax.swing.GroupLayout btnSupplierLayout = new javax.swing.GroupLayout(btnSupplier);
        btnSupplier.setLayout(btnSupplierLayout);
        btnSupplierLayout.setHorizontalGroup(
            btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupplierLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelTransaksi2)
                .addContainerGap(179, Short.MAX_VALUE))
        );
        btnSupplierLayout.setVerticalGroup(
            btnSupplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSupplierLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTransaksi2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnStatistik.setBackground(new java.awt.Color(34, 48, 96));
        btnStatistik.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnStatistik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnStatistikMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnStatistikMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnStatistikMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnStatistikMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnStatistikMouseReleased(evt);
            }
        });

        labelStatistik.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelStatistik.setForeground(new java.awt.Color(255, 255, 255));
        labelStatistik.setText("Statistik");

        iconStatistik.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconStatistik.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Icon statistik 1 2_3.png"))); // NOI18N

        javax.swing.GroupLayout btnStatistikLayout = new javax.swing.GroupLayout(btnStatistik);
        btnStatistik.setLayout(btnStatistikLayout);
        btnStatistikLayout.setHorizontalGroup(
            btnStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStatistikLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelStatistik)
                .addContainerGap(180, Short.MAX_VALUE))
        );
        btnStatistikLayout.setVerticalGroup(
            btnStatistikLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnStatistikLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnSetting.setBackground(new java.awt.Color(34, 48, 96));
        btnSetting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetting.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSettingMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSettingMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSettingMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnSettingMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnSettingMouseReleased(evt);
            }
        });

        labelSetting.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelSetting.setForeground(new java.awt.Color(255, 255, 255));
        labelSetting.setText("Setting");

        iconSetting.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconSetting.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/setting baru 2_2.png"))); // NOI18N

        javax.swing.GroupLayout btnSettingLayout = new javax.swing.GroupLayout(btnSetting);
        btnSetting.setLayout(btnSettingLayout);
        btnSettingLayout.setHorizontalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSettingLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconSetting, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelSetting)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnSettingLayout.setVerticalGroup(
            btnSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnSettingLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelSetting, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        btnDashboard.setBackground(new java.awt.Color(34, 48, 96));
        btnDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDashboardMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnDashboardMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnDashboardMouseReleased(evt);
            }
        });

        labelDashboard.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        labelDashboard.setForeground(new java.awt.Color(255, 255, 255));
        labelDashboard.setText("Dashboard");

        iconDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        iconDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/home (4) 1_2.png"))); // NOI18N

        javax.swing.GroupLayout btnDashboardLayout = new javax.swing.GroupLayout(btnDashboard);
        btnDashboard.setLayout(btnDashboardLayout);
        btnDashboardLayout.setHorizontalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(iconDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelDashboard)
                .addContainerGap(154, Short.MAX_VALUE))
        );
        btnDashboardLayout.setVerticalGroup(
            btnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(iconDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(profilePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTransaksi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnKaryawan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSupplier, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnStatistik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnSetting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addComponent(profilePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKaryawan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStatistik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        getContentPane().add(sideBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 350, 750));

        DesktopPane.setBackground(new java.awt.Color(255, 255, 255));
        DesktopPane.setLayout(new java.awt.BorderLayout());
        getContentPane().add(DesktopPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 1020, 750));

        navbar1.setBackground(new java.awt.Color(255, 255, 255));

        logoAplikasi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Logo Aplikasi.png"))); // NOI18N

        judul.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        judul.setText("Coolinary POS - Dekstop Application");

        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Close.png"))); // NOI18N
        btn_close.setBorderPainted(false);
        btn_close.setContentAreaFilled(false);
        btn_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_close.setFocusable(false);
        btn_close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout navbar1Layout = new javax.swing.GroupLayout(navbar1);
        navbar1.setLayout(navbar1Layout);
        navbar1Layout.setHorizontalGroup(
            navbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navbar1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoAplikasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(judul, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1115, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        navbar1Layout.setVerticalGroup(
            navbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, navbar1Layout.createSequentialGroup()
                .addGroup(navbar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(judul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoAplikasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 20, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(navbar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBarangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseEntered
        btnBarang.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnBarangMouseEntered

    private void btnBarangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseExited
        btnBarang.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnBarangMouseExited

    private void btnBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseClicked
        Barang barang = new Barang();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        //barang.setVisible(true);//setter halaman dashboard
        DesktopPane.add(barang).setVisible(true);//add item yang sudah di set pada dekstop pane
        btnBarang.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnBarangMouseClicked

    private void btnTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseClicked
        Transaksi transaksi = new Transaksi();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        DesktopPane.add(transaksi).setVisible(true);
        btnTransaksi.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnTransaksiMouseClicked

    private void btnTransaksiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseEntered
        btnTransaksi.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnTransaksiMouseEntered

    private void btnTransaksiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseExited
        btnTransaksi.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnTransaksiMouseExited

    private void btnKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseClicked
        Karyawan karyawan = new Karyawan();
        DesktopPane.removeAll();
        DesktopPane.repaint();
        DesktopPane.add(karyawan).setVisible(true);
        btnKaryawan.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnKaryawanMouseClicked

    private void btnKaryawanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseEntered
        btnKaryawan.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnKaryawanMouseEntered

    private void btnKaryawanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseExited
        btnKaryawan.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnKaryawanMouseExited

    private void btnSupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMouseClicked
        Supplier supplier = new Supplier();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        DesktopPane.add(supplier).setVisible(true);//add item yang sudah di set pada dekstop pane
        btnSupplier.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSupplierMouseClicked

    private void btnSupplierMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMouseEntered
        btnSupplier.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSupplierMouseEntered

    private void btnSupplierMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMouseExited
        btnSupplier.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnSupplierMouseExited

    private void btnStatistikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikMouseClicked
        Statistik statistik = new Statistik();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        DesktopPane.add(statistik).setVisible(true);
        btnStatistik.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnStatistikMouseClicked

    private void btnStatistikMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikMouseEntered
        btnStatistik.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnStatistikMouseEntered

    private void btnStatistikMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikMouseExited
        btnStatistik.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnStatistikMouseExited

    private void btnSettingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseClicked
        Setting setting = new Setting();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        DesktopPane.add(setting).setVisible(true);//add item yang sudah di set pada dekstop pane
        btnSetting.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSettingMouseClicked

    private void btnSettingMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseEntered
        btnSetting.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSettingMouseEntered

    private void btnSettingMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseExited
        btnSetting.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnSettingMouseExited

    private void btnDashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseClicked
//        btnDashboard.setBackground(new Color(101, 113, 156));
        Dashboard dashboard = new Dashboard();//instansiasi class Dashboard
        DesktopPane.removeAll();//remove item pada dekstop pane
        DesktopPane.repaint();//repaint item pada dekstop pane
        //dashboard.setVisible(true);//setter halaman dashboard
        DesktopPane.add(dashboard).setVisible(true);//add item yang sudah di set pada dekstop pane
    }//GEN-LAST:event_btnDashboardMouseClicked

    private void btnDashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseEntered
        btnDashboard.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnDashboardMouseEntered

    private void btnDashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseExited
        btnDashboard.setBackground(new Color(34, 48, 96));
    }//GEN-LAST:event_btnDashboardMouseExited

    private void btnDashboardMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMouseReleased
        btnDashboard.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnDashboardMouseReleased

    private void btnDashboardMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDashboardMousePressed
        btnDashboard.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnDashboardMousePressed

    private void btn_closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_closeActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btn_closeActionPerformed

    private void btnBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMousePressed
        btnBarang.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnBarangMousePressed

    private void btnBarangMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBarangMouseReleased
        btnBarang.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnBarangMouseReleased

    private void btnTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMousePressed
        btnTransaksi.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnTransaksiMousePressed

    private void btnTransaksiMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransaksiMouseReleased
        btnTransaksi.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnTransaksiMouseReleased

    private void btnKaryawanMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMousePressed
        btnKaryawan.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnKaryawanMousePressed

    private void btnKaryawanMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKaryawanMouseReleased
        btnKaryawan.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnKaryawanMouseReleased

    private void btnSupplierMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMousePressed
        btnSupplier.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnSupplierMousePressed

    private void btnSupplierMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSupplierMouseReleased
        btnSupplier.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSupplierMouseReleased

    private void btnStatistikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikMousePressed
        btnStatistik.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnStatistikMousePressed

    private void btnStatistikMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnStatistikMouseReleased
        btnStatistik.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnStatistikMouseReleased

    private void btnSettingMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMousePressed
        btnSetting.setBackground(new Color(91, 103, 146));
    }//GEN-LAST:event_btnSettingMousePressed

    private void btnSettingMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSettingMouseReleased
        btnSetting.setBackground(new Color(101, 113, 156));
    }//GEN-LAST:event_btnSettingMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Navbar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Navbar(null, ""); // default apabila tidak login
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane DesktopPane;
    private javax.swing.JPanel btnBarang;
    private javax.swing.JPanel btnDashboard;
    private javax.swing.JPanel btnKaryawan;
    private javax.swing.JPanel btnSetting;
    private javax.swing.JPanel btnStatistik;
    private javax.swing.JPanel btnSupplier;
    private javax.swing.JPanel btnTransaksi;
    private javax.swing.JButton btn_close;
    private javax.swing.JLabel iconBarang;
    private javax.swing.JLabel iconDashboard;
    private javax.swing.JLabel iconKaryawan;
    private javax.swing.JLabel iconSetting;
    private javax.swing.JLabel iconStatistik;
    private javax.swing.JLabel iconSupplier;
    private javax.swing.JLabel iconTransaksi;
    private javax.swing.JLabel judul;
    private javax.swing.JLabel labelBarang;
    private javax.swing.JLabel labelDashboard;
    private javax.swing.JLabel labelKaryawan;
    private javax.swing.JLabel labelSetting;
    private javax.swing.JLabel labelStatistik;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelTransaksi;
    private javax.swing.JLabel labelTransaksi2;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JLabel logoAplikasi;
    private javax.swing.JPanel navbar1;
    private javax.swing.JPanel profilePanel;
    private javax.swing.JLabel profilePicture;
    private javax.swing.JPanel sideBar;
    // End of variables declaration//GEN-END:variables
}
