/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wawonpahlawan;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Aryaaazr_
 */
public class Riwayat extends javax.swing.JFrame {

    /**
     * Creates new form Laporan
     */
    public Riwayat() {
        initComponents();
        setLocationRelativeTo(this);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        tb_penjualan.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tb_penjualan.getTableHeader().setOpaque(false);
        tb_penjualan.getTableHeader().setBackground(new Color(34, 48, 96));
        tb_penjualan.getTableHeader().setForeground(new Color(255,255,255));
        tb_penjualan.getRowHeight(25);
        tb_detailPenjualan.getTableHeader().setFont(new Font("Roboto", Font.BOLD, 12));
        tb_detailPenjualan.getTableHeader().setOpaque(false);
        tb_detailPenjualan.getTableHeader().setBackground(new Color(34, 48, 96));
        tb_detailPenjualan.getTableHeader().setForeground(new Color(255,255,255));
        tb_detailPenjualan.getRowHeight(25);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tb_detailPenjualan = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_penjualan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnPilih = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_detailPenjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "No", "No", "No"
            }
        ));
        jScrollPane2.setViewportView(tb_detailPenjualan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 330, 270));

        tb_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "No", "No", "No"
            }
        ));
        jScrollPane1.setViewportView(tb_penjualan);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 340, 270));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/textFieldRiwayat.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 180, 220, 30));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/label Strip.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 40, 30));

        btnPilih.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Pilih.png"))); // NOI18N
        btnPilih.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPilih.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPilih.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPilihMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPilihMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnPilihMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnPilihMouseReleased(evt);
            }
        });
        getContentPane().add(btnPilih, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 170, 90, 50));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/textFieldRiwayat.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 220, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Background Laporan.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPilihMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseEntered
        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Pilih_Hover.png")));
    }//GEN-LAST:event_btnPilihMouseEntered

    private void btnPilihMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseExited
        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Pilih.png")));
    }//GEN-LAST:event_btnPilihMouseExited

    private void btnPilihMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMousePressed
        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Pilih_Press.png")));
    }//GEN-LAST:event_btnPilihMousePressed

    private void btnPilihMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPilihMouseReleased
        btnPilih.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/Button Pilih_Hover.png")));
    }//GEN-LAST:event_btnPilihMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Riwayat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Riwayat().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel btnPilih;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tb_detailPenjualan;
    private javax.swing.JTable tb_penjualan;
    // End of variables declaration//GEN-END:variables
}
